### ISSUE TITLE
Dupe polluted water output calculation is wrong

### ISSUE THREAD

**Issue by brandonegbert** [david-j-lee/oni-calc#4]
![screenshot from 2018-07-28 13-25-31](https://user-images.githubusercontent.com/11236365/43360461-983b5cac-926a-11e8-99ad-8e1570ae52ce.png)

See the screenshot.  Not sure what's going on here but 12 dupes producing 11,500g of polluted water (ie a lavatory) each should be 138,000 in output.  I have no idea where the 230 number is coming from.

**Comment by david-j-lee** [comment]
@brandonegbert So the input is for per cycle whereas the left panel is per second. In order to convert per cycle to per second, I divide the output by 600 (600 seconds in a cycle). So 138,000 grams per cycle would result in 230 grams per second.

**Comment by brandonegbert** [comment]
The water is off then.  It's coming out to 5,000*12=60,000.

**Comment by david-j-lee** [comment]
@brandonegbert Nice catch, the negative numbers did not perform the conversion to per second correctly. I have updated GitHub with the [1ca68e2](https://github.com/david-j-lee/oni-calc/commit/785373413f641d40008e91496db3599527aac33e) commit and the live site. Thank you.
