### ISSUE TITLE
Mirror sites

### ISSUE THREAD

**Issue by zsnmwy** [david-j-lee/oni-calc#5]
First,I have to say your website is very useful.

I recommend to my friends.

Unfortunately,we always get the error code when browser the web site in China.

Because the server is far away from my location. China ----- USA

I want to make a mirror site in China.

Can you allow me to do this?

Thanks.

**Comment by david-j-lee** [comment]
@zsnmwy Sure thing, appreciate you asking first. Let me know if there is anything I can do to help.   :)

I am currently hosting this on AWS, if you know how to get this setup for China on AWS please let me know. I have been fixing a lot of bugs lately and would be nice to keep the website in China up to date.
